# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be006a58c5ef3dc4f3bf5f0a9887b66cce16053aef55dfa1d9f7673fc6faf2e5317c0a6376852e5e58977c47b5c815186c9572f01f97739b65ebb3e12e4dac46

test:
  secret_key_base: da15c9d3f5afefa6de8f8e73ea1f1d786b13a0f34349c61e8bc364be65633b6c363927800d48b07d0c1c2046b22b00178e8d091a14016cd3c80902e0b4522177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
